# -*- coding: utf-8 -*-
"""PCA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zUDnnBOOGv5Tgu8mZtQjmKM4HWNdoHEd
"""

from sklearn.datasets import load_iris
iris=load_iris()
iris_data=iris.data
iris_data.shape

iris_labels=iris.target
iris_labels.shape

import numpy as np
labels=np.reshape(iris_labels,(150,1))

final_iris_data=np.concatenate([iris_data,labels],axis=1)
final_iris_data.shape

import pandas as pd
iris_dataset=pd.DataFrame(final_iris_data)
features=iris.feature_names
features

features_label=np.append(features,'label')

iris_dataset.columns=features_label
iris_dataset.head()

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(iris_dataset)

scaled_data=scaler.transform(iris_dataset)

scaled_data

from sklearn.decomposition import PCA
pca=PCA(n_components=2)
pca.fit(scaled_data)

x_pca=pca.transform(scaled_data)

scaled_data.shape

x_pca.shape

scaled_data

x_pca

import matplotlib.pyplot as plt
plt.figure(figsize=(8,6))
plt.scatter(x_pca[:,0],x_pca[:,1],c=iris['target'])
plt.xlabel('First principle component')
plt.ylabel('Second principle component')